### ISSUE TITLE
Question About CRAN Release of imager

### ISSUE THREAD

**Issue by ShotaOchi** [dahtah/imager#102]
@dahtah,
Are you going to submit the newest version of imager to CRAN?

**Comment by dahtah** [comment]
Hi! I intend to, but it's a ton of work (I hit a bug in devtools, ccache doesn't work anymore for mysterious reasons, need to update CImg, some bullshit requests from CRAN to deal with, etc.) Looks like a full day of work at the very least and I really can't spare the time at this point

**Comment by ShotaOchi** [comment]
I understand.
Take it easy.
