### ISSUE TITLE
fsize parameter in `draw_text` not working

### ISSUE THREAD

**Issue by niedermansam** [dahtah/imager#108]
Changing the value of `fsize` doesn't seem to do anything.

```r
color = "#AA3939"

imfill(200, 200, val = color) %>%
  draw_text(x = 10, y = 10, text = color, color = "white", fsize = 20) %>%
  plot(axes=F)

imfill(200, 200, val = color) %>%
  draw_text(x = 10,y = 10 , text = color, color = "white", fsize = 80) %>%
  plot(axes=F)
```

I am using imager version `0.41.2` on Windows 10.

**Comment by ShotaOchi** [comment]
The error has been fixed in the development version of imager.
See #94.

You can install the windows binary of the development version from
https://github.com/ShotaOchi/imager/releases/download/0.41.1/imager_0.41.1.zip
