### ISSUE TITLE
overlaying and stacking images

### ISSUE THREAD

**Issue by jpmarindiaz** [dahtah/imager#11]
How can I overlay an image to another image given some x,y pixels? is that possible in `imager`?

If I have two images, how can I make a new images by putting them together side by side?
This is what I am doing right now: stacking arrays. 
```
library(abind)
  x <- abind(img1, img2, along = 1)
  x <- as.cimg(x)
```
I was wondering if there is some function in ìmager` to handle this.
Thanks for the help!

**Comment by dahtah** [comment]
To overlay images, use imdraw, see ?imdraw. To bind images together, see 
imappend:

imappend(img1,img2,"x") #Bind horizontally
imappend(img1,img2,"x") #Bind vertically
