### ISSUE TITLE
Question about "verify that the new mechanism which is supposed to detect that X11 is missing on MacOS actually works"

### ISSUE THREAD

**Issue by ShotaOchi** [dahtah/imager#114]
I don't understand what the sentence means.

Now, imager detects X Window System according to the configure file.
Doesn't it work on mac OS?

**Comment by dahtah** [comment]
It's supposed to (I got it from some other package) but hasn't been tested yet because I don't have access to a Mac.

**Comment by ShotaOchi** [comment]
CRAN didn't say anything about the detection mechanism of X11 on mac.
