### ISSUE TITLE
Question about "Vignettes are supposed to be self-contained"

### ISSUE THREAD

**Issue by ShotaOchi** [dahtah/imager#115]
I built R with clang on fedora from the source (https://svn.r-project.org/R/trunk).
However, I can't find an option to check whether vignettes are self-contained.
R CMD check without options didn't warn of vignettes.
What should we do?

**Comment by dahtah** [comment]
I think we may want to submit to CRAN and see if they complain, the original email wasn't very helpful

**Comment by Ax3man** [comment]
I don't think you can call packages like `scales` and `dplyr` functions in your vignettes, unless you place them in your Suggests. When users install all packages listed in the Description, they should be able to build the vignettes (i.e. they should not depend on packages only listed in the vignettes). 

[See Hadley's book.](http://r-pkgs.had.co.nz/vignettes.html#vignette-cran)

As the email said, this should normally be flagged by R CMD check, but apparently it isn't, which Ripley blames on the "tangles" being wrong. I don't know what that means.

**Comment by ShotaOchi** [comment]
CRAN didn't say anything about vignettes.
