### ISSUE TITLE
hough_circle function doesn't work properly

### ISSUE THREAD

**Issue by ShotaOchi** [dahtah/imager#128]
@dahtah 
I received an e-mail that reported hough_circle function didn't work properly, and I confirmed it.
We can confirm it by running the code shown below.
``` 
library(imager)
px <- enorm(imgradient(px.circle(100, 300, 300), "xy")) > 0
hc <- hough_circle(px, 100)
plot(hc)
```
plot(hc) shows us blank image.

It seems that there is a problem in hough_circle_ function.
https://github.com/dahtah/imager/blob/master/src/hough.cpp#L62-L76

What do you think?

**Comment by garcia-nacho** [comment]
Same problem here. Even the example doesn't work and it worked before. 
You can make it work by using the old library:

library(devtools)

install_version("imager", version = "0.41.1", repos = "http://cran.us.r-project.org")

**Comment by dahtah** [comment]
Thanks for reporting this, something must have changed in CImg. Should be fixed in the latest master, please check!

**Comment by ShotaOchi** [comment]
Thank you for fixing hough_circle function.
