### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by under-score** [dahtah/imager#13]
Get an error in dyn.load(file, DLLpath = DLLpath, ...) on 2 Macs with OS X El Capitan. The file seems to exist.

  kann shared object '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/imager/libs/imager.so' nicht laden:
  dlopen(/Library/Frameworks/R.framework/Versions/3.3/Resources/library/imager/libs/imager.so, 6): Library not loaded: /opt/X11/lib/libX11.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.3/Resources/library/imager/libs/imager.so

**Comment by dahtah** [comment]
Is XQuartz installed?

**Comment by under-score** [comment]
Super. Thank you.  Needs https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.9.dmg installed outside RStudio.
