### ISSUE TITLE
Pixel-wise median averaging, ala GMIC?

### ISSUE THREAD

**Issue by mconsidine** [dahtah/imager#134]
Hi,
I would like to manipulate image layers directly with imageR, rather than playing around with them as layers in GIMP.  Specifically, I'd like to combine layers to improve signal-to-noise ratios and use things like differences, median averaging, weighted averaging, etc.

I know GMIC-Qt/GIMP is closely related to CImg as is imageR.  Does anyone know how to
- do pixel-wise median averaging of an image list?
- even better: import the library of filters in GMIC-Qt to be able to use them in imageR or a command-line mode?

Thank you!
Matt

**Comment by dahtah** [comment]
Hi Matt, have a look at the parmed function, I think it does what you're looking for.

**Comment by mconsidine** [comment]
Thanks, I'll take a look at parmed ...

**Comment by mconsidine** [comment]
Yes, parmed works for the median-averaging that I was looking for.  Second part of the question still stands, but I'll try dealing with that later.
