### ISSUE TITLE
Overwrite axis in plot function

### ISSUE THREAD

**Issue by MartinRoth** [dahtah/imager#14]
For displaying it might be nice to have empty labels, but

$ plot(boats, xlab="")

results in:
Error in plot.default(c(1, w), c(1, h), type = "n", xlab = "x", ylab = "y",  : 
  formal argument "xlab" matched by multiple actual arguments

**Comment by dahtah** [comment]
Good point, thanks. Fixed in dev branch:

    devtools::install_github("dahtah/imager",ref="cxxplugin")
