### ISSUE TITLE
the result from as.cimg %>% plot is different from magick::image_read %>% plot  or as.raster

### ISSUE THREAD

**Issue by rpsantosa** [dahtah/imager#145]
the result from as.cimg %>% plot
 is different from 
magick::image_read %>% plot  or 
as.raster %>% plot
( the last 2 are equal, and different from cimg output)
![cimg](https://user-images.githubusercontent.com/29023947/111122355-b542e180-854c-11eb-892f-4d348e44624d.png)
![asraster_or_image_load](https://user-images.githubusercontent.com/29023947/111122359-b6740e80-854c-11eb-9aa8-bdb6999d380a.png)

**Comment by ShotaOchi** [comment]
What happens if you use magick2cimg function?
magick2cimg function works well on my computer.
```
img <- image_read("the_image.png")
magick2cimg(img) %>% plot
```

**Comment by rpsantosa** [comment]
I found out that imager do some preprocessing, normalizing the colors, what gives better results on some images.
