### ISSUE TITLE
ERROR with Dowload.file

### ISSUE THREAD

**Issue by Nachoeigu** [dahtah/imager#147]
Hi everyone, I have an issue in R.
I wanted to download my historical data from Lichess with this link (lichess.org/api/games/user/Nachoeigu), but when I use the download.file, I received an error.

I will show you my code:

> 
> url <- "lichess.org/api/games/user/Nachoeigu"
> 
> destfile <- "C:/Users/Sol/Downloads/nachoeigu_chess.pgn"
> 
> download.file(url, destfile, method = "libcurl")

The error I receive is this: 

> download.file(url, destfile, method = "libcurl")
> 
> trying URL 'lichess.org/api/games/Nachoeigu'
> 
> Content length 162 bytes
> 
> Error in download.file(url, destfile, method = "libcurl") : 
>   cannot open URL 'lichess.org/api/games/Nachoeigu'
> 
> In addition: Warning message:
> 
> In download.file(url, destfile, method = "libcurl") :
>   URL 'https://lichess.org/api/games/Nachoeigu': status was 'SSL connect error'
> 

Thank you guys for read my issue.

**Comment by ShotaOchi** [comment]
download.file function is not a function of imager.
This issue should not be posted here.
You should post this issue on stackoverflow or Rstudio Community.
