### ISSUE TITLE
More detailed imsharpen docs

### ISSUE THREAD

**Issue by DarrenCook** [dahtah/imager#15]
For these three, the default values are 1, 0, 0, and the descriptions are:
  edge: Edge threshold (shock filters only).
  alpha: Gradient smoothness (shock filters only).
  sigma: Tensor smoothness (shock filters only).

It gives no description on the possible ranges (are they 0.0 to 1.0, or 0 to 255?), or values that might be successful for different applications. So far I've only found this, suggesting sigma values of 0.0, 0.5, 1.0, 2.0 or 5.0.  (I assume higher meaning more smoothing?)  http://www.halcon.com/download/reference/shock_filter.html   But no hints for edge or alpha.

BTW, the `sharpen_type` argument would be more R-like if it was a string parameter: "diffusion" vs. "shock", or something like that. If keeping it as a bool, it might be better to rename it as `use_shock_filters` ?

**Comment by dahtah** [comment]
You're quite right about the state of the documentation. In this case 
it's what I copied and pasted directly from CImg's doc, and it's a bit 
lacking. I'll have to have a look at the source to figure out exactly 
what the algorithm is doing.
You're also right about string parameters, I'm planning a more 
systematic overhaul.
