### ISSUE TITLE
Is it okay to rewrite the vignettes to reduce the package size?

### ISSUE THREAD

**Issue by ShotaOchi** [dahtah/imager#152]
@dahtah 
CRAN required me to fix the gcc 11 issues and I submitted the fixed version of imager.
However, the size of the source exceeds the limit 5MB.
That's why imager is pending now and we must reduce the size of the source.

An idea is to remove the external images but the external images is used in the vignettes.
Is it okay to rewrite the vignettes to reduce the package size?

**Comment by dahtah** [comment]
Sure! One quick hack that may suffice is to reduce the default quality of the images produced by knitr by increasing jpeg compression level, right now there's an option 
``` dev.args=list(quality=50) ```
which can be reduced further if needed

**Comment by ShotaOchi** [comment]
Thank you for your advice.
I reduced the size of the source without removing the external images and submitted imager 0.42.10.
I believe CRAN will accept it soon.
