### ISSUE TITLE
how to cite imager package?

### ISSUE THREAD

**Issue by ShotaOchi** [dahtah/imager#154]
@dahtah 
I received an e-mail from a post-doctoral researcher.
He wants to know how to cite imager package to publish his paper.
How should he cite imager package?

**Comment by dahtah** [comment]
There's a JOSS article people can cite if they wish to: 
Barthelmé, S., & Tschumperlé, D. (2019). imager: an R package for image processing based on CImg. Journal of Open Source Software, 4(38), 1012.

**Comment by ShotaOchi** [comment]
Thanks.
I told him he could cite the article.
