### ISSUE TITLE
Error Installing imager on the RStudio Cloud

### ISSUE THREAD

**Issue by bkostadi** [dahtah/imager#161]
I have been trying for some time to install imager on the **RStudio Cloud**, but the compilation always fails with a fatal error:

```
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make: *** [/opt/R/4.1.2/lib/R/etc/Makeconf:177: colourspace.o] Error 1
ERROR: compilation failed for package ‘imager’
* removing ‘/cloud/lib/x86_64-pc-linux-gnu-library/4.1/imager’
```

Can you please suggest a way to resolve this error and install **imager** on the **RStudio Cloud**?

**Comment by ShotaOchi** [comment]
The error message means the RAM size is not enough.
You have to upgrade your plan of RStudio Cloud to compile imager.

**Comment by bkostadi** [comment]
Thank you so much for the prompt response and for your help! Yes, you are right, the reason for the error was the insufficient RAM.

**Comment by bkostadi** [comment]
Thank you so much for the prompt response and for offering your help! Much appreciated. 

Yes, you are right! The problem was the RAM size. The default RAM on the RStudio Cloud was just 1GB, but I increased it to 4GB and managed to install imager. 

Thanks again for your help!

All the best,
Boyan
