### ISSUE TITLE
Support 1-row data frame

### ISSUE THREAD

**Issue by DarrenCook** [dahtah/imager#18]
```
row <- data.frame(t(runif(64)))
as.cimg(row, x=8, y=8)
```
Gives a confusing error: "Error in function_list[[k]](value) : Variable value is missing"

The solution is:

`as.cimg(unlist(row), x=8, y=8)`

Can the library do the unlist automatically? I think this might be the most common use-case?

There might be a more elegant way, but I think adding this line to the top of `imager:::as.cimg.data.frame()` will do it:

`if(nrow(obj) == 1)obj <- unlist(obj)`

**Comment by dahtah** [comment]
Thanks for the bug report! Originally the intent of as.cimg.data.frame was to do the reverse of as.data.frame.cimg, namely to take a data frame of format (x,y,value). From that perspective a one-row data.frame is a bit strange, so I'm leaning towards issuing an error. Would you agree?

**Comment by DarrenCook** [comment]
Interesting; I have the bitmap data in a data frame, one row per image. I've not used/needed `as.data.frame.cimg`, but I agree that maintaining the bi-directional conversion is important. Now I see why that code, expecting a column called "value", was in there.

Do you ever expect to have 1 pixel images being imported/exported from/to data frames? If not, the nrow(obj)==1 check is not going to break anything. But if 1px images are possible, also checking for a "value" column should be enough to make it safe?

**Comment by dahtah** [comment]
Fixed, as.data.frame.cimg now supports edge cases like 
```
as.cimg(data.frame(x=1,value=1))
as.cimg(data.frame(y=1:10,value=1))
```
Thanks for your input!
