### ISSUE TITLE
Switch off anti-aliasing?

### ISSUE THREAD

**Issue by DarrenCook** [dahtah/imager#20]
When plotting small images, the anti-alias effect is sometimes undesirable. With 5x5 pixel images it is quite extreme: I want to see the individual pixels, and cannot!
Is there anyway to turn this off, or is it being done by R processes underneath the Imager library?

**Comment by dahtah** [comment]
Good point. The anti-aliasing is turned on by default for rasters in R, but there should be an option for switching it off. 
I've just submitted imager v0.30 to CRAN, but I'll fix that in the next release. In the meanwhile:
```
im <- imnoise(5,5)
as.raster(im) %>% plot(interpolate=FALSE)
```
You can also use ggplot2: 
```
as.data.frame(im) %>% ggplot(aes(x,y))+geom_tile(aes(fill=value))+scale_y_reverse()
```

**Comment by DarrenCook** [comment]
That was quick! I was about to post I was getting useful results with:
  `image(as.matrix(im), col=grey(seq(0, 1, length = 256)), axes=F)`

But your `plot(as.raster(m), interpolate=F)` has square pixels (and is also the right way up; I've just realized that image() is flipping images).

**Comment by dahtah** [comment]
Version 0.31 now include an option for turning anti-aliasing off. 
```
matrix(1:9,3,3)  %>% as.cimg %>% plot(interp=FALSE)
```
