### ISSUE TITLE
cimg::load_network(): Failed to load file

### ISSUE THREAD

**Issue by KarthiAru** [dahtah/imager#29]
I get the following error when I run `load.image("https://cran.r-project.org/Rlogo.jpg")`

```
sh: -c: line 0: unexpected EOF while looking for matching `"'
sh: -c: line 1: syntax error: unexpected end of file
Error in eval(substitute(expr), envir, enclos) : 
  cimg::load_network(): Failed to load file 'https://cran.r-project.org/Rlogo.jpg' with external commands 'wget' or 'curl'.
```

**Environment:**
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

**Comment by dahtah** [comment]
CImg relies on wget or curl to grab urls, are either installed on your 
system?

You can also use this as a workaround (I'll add it to the next version 
of imager):

```
install.package("downloader")
load.url <- function(url) { f <- tempfile(); 
downloader::download(url,f); im <- load.image(f); unlink(f); im }
load.url("https://cran.r-project.org/Rlogo.jpg") %>% plot
```
