### ISSUE TITLE
issue convert: delegate failed `"ffmpeg" with mpeg

### ISSUE THREAD

**Issue by kruny1001** [dahtah/imager#3]
> tennis <- load.image(system.file('extdata/tennis_sif.mpeg',package='imager'))
convert: delegate failed `"ffmpeg" -nostdin -v -1 -i "%i" -vframes %S -vcodec pam -an -f rawvideo -y "%u.pam" 2> "%Z"' @ error/delegate.c/InvokeDelegate/1332.
convert: unable to open image `/var/tmp/magick-50575o_bXKN24kYIc.pam': No such file or directory @ error/blob.c/OpenBlob/2695.
convert: no images defined `pnm:-' @ error/convert.c/ConvertImageCommand/3230.
sh: gm: command not found
Error: [instance(0,0,0,0,0x0,non-shared)] CImg<double>::load(): Failed to recognize format of file '/Users/kruny1001/Library/R/3.2/library/imager/extdata/tennis_sif.mpeg'.
> play(tennis)
Error in play(tennis) : object 'tennis' not found
> #now filter in the time direction and pipe to play
> deriche(tennis,10,axis="z") %>% play
Error in deriche(tennis, 10, axis = "z") : object 'tennis' not found

I can run png image with your sample code but I can't run the video with your example. What am I missing?

**Comment by dahtah** [comment]
You need ffmpeg to load videos. It says so in the documentation but I should probably make it clear in an error message as well. This one's pretty obscure.

**Comment by kruny1001** [comment]
I did install ffmpeg on my mac by brew install ffmpeg. but I still see the error message.

**Comment by dahtah** [comment]
Have you installed imagemagick as well? Looks like the missing executable (gm) is actually from imagemagick, not ffmpeg (my mistake).

**Comment by kruny1001** [comment]
I did. I installed imagemagic, ffmpeg and other prerequired library. I am running this on my mac

**Comment by dahtah** [comment]
Can you please try: 
brew install graphicsmagick
and tell me if "gm" returns anything in the terminal?

**Comment by kruny1001** [comment]
-MacBook-Pro:~$ gm
-bash: gm: command not found
-MacBook-Pro:~$ brew install graphicsmagick
==> Downloading https://homebrew.bintray.com/bottles/graphicsmagick-1.3.21.yosem
######################################################################## 100.0%
==> Pouring graphicsmagick-1.3.21.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/graphicsmagick/1.3.21: 467 files, 13M
-MacBook-Pro:~$ gm
GraphicsMagick 1.3.21 2015-02-28 Q8 http://www.GraphicsMagick.org/
Copyright (C) 2002-2014 GraphicsMagick Group.
Additional copyrights and licenses apply to this software.
See http://www.GraphicsMagick.org/www/Copyright.html for details.
Usage: gm command [options ...]

Where commands include: 
      batch - issue multiple commands in interactive or batch mode
  benchmark - benchmark one of the other commands
    compare - compare two images
  composite - composite images together
    conjure - execute a Magick Scripting Language (MSL) XML script
    convert - convert an image or sequence of images
       help - obtain usage message for named command
   identify - describe an image or image sequence
    mogrify - transform an image or sequence of images
    montage - create a composite image (in a grid) from separate images
       time - time one of the other commands
    version - obtain release version
MacBook-Pro:~ $ 

After install graphicsmagick. I tried run the sample code from rStudio
I can still see the same error messages 

> library(imager)
Loading required package: plyr
Loading required package: magrittr
Loading required package: stringr
Loading required package: png
Loading required package: jpeg

Attaching package: ‘imager’

The following object is masked from ‘package:magrittr’:

    add

The following object is masked from ‘package:plyr’:

    liply

The following objects are masked from ‘package:stats’:

    convolve, spectrum

The following object is masked from ‘package:graphics’:

    frame

The following object is masked from ‘package:base’:

    save.image

> tennis <- load.image(system.file('extdata/tennis_sif.mpeg',package='imager'))
convert: delegate failed `"ffmpeg" -nostdin -v -1 -i "%i" -vframes %S -vcodec pam -an -f rawvideo -y "%u.pam" 2> "%Z"' @ error/delegate.c/InvokeDelegate/1332.
convert: unable to open image `/var/tmp/magick-25902iqF0P0m51egQ.pam': No such file or directory @ error/blob.c/OpenBlob/2695.
convert: no images defined `pnm:-' @ error/convert.c/ConvertImageCommand/3230.
sh: mpeg2decode: command not found
gm convert: Unable to open file (/var/folders/70/d3g1lc394k163j9bw8h68f8c0000gn/T/gmtK8MYB*.ppm) [No such file or directory].
gm convert: Unable to open file (/var/folders/70/d3g1lc394k163j9bw8h68f8c0000gn/T/gmh4FOq5).
Error: [instance(0,0,0,0,0x0,non-shared)] CImg<double>::load(): Failed to recognize format of file '/Users/kruny1001/Library/R/3.2/library/imager/extdata/tennis_sif.mpeg'.
> play(tennis)
Error in play(tennis) : object 'tennis' not found
> #now filter in the time direction and pipe to play
> deriche(tennis,10,axis="z") %>% play
Error in deriche(tennis, 10, axis = "z") : object 'tennis' not found
>

**Comment by dahtah** [comment]
Looks like there's a problem with either CImg, ffmpeg or ImageMagick. I'm going to try reporting as a CImg issue, see if the author has any idea what could be going on.

**Comment by dahtah** [comment]
Have a look at dtschump's response:
https://github.com/dtschump/CImg/issues/14

**Comment by kruny1001** [comment]
thanks
