### ISSUE TITLE
how to swapaxes?

### ISSUE THREAD

**Issue by pjpan** [dahtah/imager#31]
Hi ,
how can I  do the following transformation，swap axes to make image from (224, 224, 3) to (3, 224, 224)

- python code: 
```
    sample = np.swapaxes(sample, 0, 2)
    sample = np.swapaxes(sample, 1, 2)
```
the origin image is a 4D arrays,like (224.224.1.3). I want to change it to (1,3,244,244).

**Comment by dahtah** [comment]
Try permute_axes. The normal ordering is "xyzc", so:
```
permute_axes(im,"czxy") 
```
should be what you're looking for

**Comment by pjpan** [comment]
Thanks,that is what I looking for.
