### ISSUE TITLE
support for LabtoRGB and RGBtoLab

### ISSUE THREAD

**Issue by gmculp** [dahtah/imager#37]
Is there a plan to support [LabtoRGB](http://cimg.eu/reference/structcimg__library_1_1CImg.html#ad97f91d4a4227ad419ba0ddd85aef0e5) and [RGBtoLab](http://cimg.eu/reference/structcimg__library_1_1CImg.html#a113684f98f6c6da7511c7b6d66ad4efa)?  

Thanks.
GMC

**Comment by dahtah** [comment]
Yes, they're in the dev branch ("pixset"), as "sRGBtoLab" and "LabtosRGB". If you're on OS X/Linux you can install the dev branch pretty easily using devtools, if you're on Windows I'm planning on finalising imager 0.40 soon and updating on CRAN.

**Comment by gmculp** [comment]
Thank you, Simon!
