### ISSUE TITLE
"TIFF" format images seem not to be properly converted

### ISSUE THREAD

**Issue by aTnT** [dahtah/imager#39]
Here's an image example (file can be [downloaded here](http://www.filedropper.com/194336662036921212017)):

```
> iminfo(image_path)

$name
[1] "19_433666_203692_1212017.tif"

$format
[1] "TIFF"

$width
[1] 256

$height
[1] 256

$size
[1] 327221
```

This is how the image normally looks (using imagemagick):

![image](https://cloud.githubusercontent.com/assets/3149376/23062166/0678137c-f505-11e6-8e8d-438f7c01acf5.png)

When running:

```
> load.image(image_path) %>% display()
```

I get:

![image](https://cloud.githubusercontent.com/assets/3149376/23062287/77440aac-f505-11e6-8546-967909c36a11.png)

I get the same result with plot().

When saving the image object back to tif with save. image() and opening with imagemagick i get the same result:

![image](https://cloud.githubusercontent.com/assets/3149376/23063152/4bcd7b34-f509-11e6-9bc1-51a1c16af4e6.png)

This is my sessionInfo()

```

R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=nl_NL.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=nl_NL.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=nl_NL.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=nl_NL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] dplyr_0.5.0     purrr_0.2.2     readr_1.0.0     tidyr_0.6.1     tibble_1.2     
 [6] ggplot2_2.2.1   tidyverse_1.1.1 imager_0.31     magrittr_1.5    plyr_1.8.4     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9      forcats_0.2.0    tools_3.3.2      lubridate_1.6.0  jsonlite_1.2    
 [6] nlme_3.1-128     gtable_0.2.0     lattice_0.20-34  png_0.1-7        psych_1.6.12    
[11] DBI_0.5-1        parallel_3.3.2   haven_1.0.0      readbitmap_0.1-4 bmp_0.2         
[16] xml2_1.1.1       httr_1.2.1       stringr_1.1.0    hms_0.3          grid_3.3.2      
[21] R6_2.2.0         jpeg_0.1-8       readxl_0.1.1     foreign_0.8-67   modelr_0.1.0    
[26] reshape2_1.4.2   scales_0.4.1     rvest_0.3.2      assertthat_0.1   mnormt_1.5-5    
[31] colorspace_1.3-2 stringi_1.1.2    lazyeval_0.2.0   munsell_0.4.3    broom_0.4.2    
```

**Comment by dahtah** [comment]
It looks like your TIFF file is pretty exotic. The gimp won't read it (Unsupported layout), eog won't read it, and in R tiff::readTIFF won't load it either. How was it produced?

**Comment by aTnT** [comment]
It was produced with [raster::writeRaster](https://www.rdocumentation.org/packages/raster/versions/2.5-8/topics/writeRaster), using the "GTiff" format. I am making a work around by creating a separate .jpg, load it and process it on imager. Will merge later the geospatial information or covert it to a raster object later, [doing something like this](https://cran.r-project.org/web/packages/magick/vignettes/intro.html#the_raster_package).

**Comment by dahtah** [comment]
So if I understand correctly what you need is a direct way of converting a raster object to a cimg object?

**Comment by dahtah** [comment]
I know next to nothing about spatial data but it sounds like the file created by raster is actually in GTif format, not standard TIFF.

**Comment by aTnT** [comment]
It would be definitely a useful feature to have a direct conversion between raster objects and cimg objects, to process the spatial content of the image with image processing techniques. A GeoTiff is in essence a Tiff with extra tags with spatial information, such as geographical reference frame and projection system, meaning that each pixel is georeferenced.

**Comment by dahtah** [comment]
OK, now that I've had a quick look: 
- The initial problem with the GeoTIFF file produced by writeRaster is due to the fact that rgdal produces by defaut float-valued TIFF files, which other libraries don't expect (they expect integer values). I'll have to kick this one upstairs to the author of CImg. If you save your rasters using integer values, it does work:
```
library(raster)
library(imager)
tmp <- tempfile(fileext=".tif")
writeRaster(logo,tmp,datatype="INT2S",overwrite=TRUE)
logo <- raster(system.file("external/rlogo.grd", package="raster")) 
load.image(tmp) %>% plot
```
- To directly convert raster data to the cimg format, you could try this: 

```
##adapted from the image method for RasterLayer objects
##by Robert J Hijmans
as.cimg.RasterLayer <- 
	function(x, maxpixels=1e7, ...)  {
		x <- sampleRegular(x, maxpixels, asRaster=TRUE, useGDAL=TRUE)
		y <- yFromRow(x, nrow(x):1)
                                        #value <- t(as.matrix(x)[nrow(x):1, ,drop=FALSE])
                value <- as.vector(x) %>% t
		x <- xFromCol(x,1:ncol(x))
                array(value,c(length(x),length(y),1,1)) %>% as.cimg 
	}

as.cimg(logo) %>% plot
```

There's a maxPixels argument so that it won't by tempted to load a huge amount of out-of-memory data. 
Can you please let me know if that does the job? 

Note that the main branch of imager does not support NAs *at all*. There's some very preliminary, very limited support in the current dev branch ("pixset"), so you if you have missing values in your raster data you might want to use the latest branch instead.

**Comment by aTnT** [comment]
Thanks, for the clarification, that makes sense and it works! In my case (and i guess in most use geospatial data use ases where conversion from a raster to cimg object is needed), the pixels represent information of a geospatial object type, so integers work fine. Since many (Geo)Tiff files are multiband, one can use [imager's image lists](http://dahtah.github.io/imager/imager.html#image-lists) to process each band. So your example work fine! Maybe would be nice to add your example in a the vignette on how to convert from the raster class? Congrats for the imager package and clean documentation, the R community was missing an image processing package like this for a while.
