### ISSUE TITLE
Error: sudo yum install -y libfftw3* libX11*

### ISSUE THREAD

**Issue by englianhu** [dahtah/imager#4]
I am using centOS7 and tried to install
```
$ sudo yum install -y libfftw3* libX11*
```
However there has below error:
![capture](https://cloud.githubusercontent.com/assets/7227582/12701008/49d80cda-c83d-11e5-9af2-4c123a600f79.JPG)

**Comment by dahtah** [comment]
That's a dependency coming from the readbitmap package. Install libjpeg and libpng:
sudo yum install -y libjpeg* libpng*
(I imagine that will work on your system but I'm not sure, running Ubuntu here).
I'll update the doc, thanks.

**Comment by englianhu** [comment]
Tried to install 
```
sudo yum -y install libjpeg*
```
but there has another error which is an fatal error : *fftw3.h : no such directory* while I've `sudo yum install -y libfftw* fftw*`

**Comment by englianhu** [comment]
installed, thx god. =="
