### ISSUE TITLE
Error in download.file(url, method = method, ...)

### ISSUE THREAD

**Issue by Jeet1994** [dahtah/imager#45]
I am trying to reproduce your code that is given [here](https://dahtah.wordpress.com/2017/03/24/superpixels-in-imager/).

When I run the following code:
```R
im <- load.image("https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Aster_Tataricus.JPG/1024px-Aster_Tataricus.JPG")
```
I get the following error:
```R
trying URL 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Aster_Tataricus.JPG/1024px-Aster_Tataricus.JPG'
Error in download.file(url, method = method, ...) : 
  cannot open URL 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Aster_Tataricus.JPG/1024px-Aster_Tataricus.JPG'
```
**How do I solve this error?**
I am working on an Windows 8 machine. 

Also, is there a method to load locally downloaded images into Rstudio using imager?

**Comment by Jeet1994** [comment]
Okay, so I solved this issue myself. 

However, to put it up for beginners who are starting, I would like to point out that this is happening because RStudio uses Internet Explorer ( :-1: ) as its default browser. 

So just go and set [upload.wikimedia.org](upload.wikimedia.org) to the **trusted sites** lists. 

Restart RStudio and it will work. :+1:

**Comment by Jeet1994** [comment]
I would still like a **new feature** of loading locally downloaded images though. :bowtie:

**Comment by Jeet1994** [comment]
Problem solved.

**Comment by dahtah** [comment]
Thanks for reporting this. I think it's a problem with the downloader package, rather than with imager, but I'll investigate. Does the issue occur because the URL uses https and not http? 
Also, I'm not sure I understand what you mean by "loading locally downloaded images"? You can use load.image to load images from the hard drive. Did you have something else in mind?

**Comment by Jeet1994** [comment]
Thanks for the input, that worked. I would like to add more to the README of this repo. How do I contribute? :smiley:

**Comment by dahtah** [comment]
If you'd like to contribute, you can fork the repo and send me a pull request, as [explained here](https://guides.github.com/activities/forking/). Happy to take contributions!

**Comment by alnafisa001** [comment]
Hi,
I have problem in this part:
#400 superpixels
out <- slic(im,400)
#Superpixels
plot(out$sp,axes=FALSE)
#Segmentation
plot(out$seg,axes=FALSE)
#Show segmentation on original image
(im*add.colour(abs(imlap(out$seg)) == 0)) %>% plot(axes=FALSE)

This is the massage that I had fro R code:
> out <- slic(im,400)
Error in function_list[[i]](value) : could not find function "map_dbl"
> #Superpixels
> plot(out$sp,axes=FALSE)
Error in plot(out$sp, axes = FALSE) : 
  error in evaluating the argument 'x' in selecting a method for function 'plot': Error in out$sp : $ operator is invalid for atomic vectors
> #Segmentation
> plot(out$seg,axes=FALSE)
Error in plot(out$seg, axes = FALSE) : 
  error in evaluating the argument 'x' in selecting a method for function 'plot': Error in out$seg : $ operator is invalid for atomic vectors
> #Show segmentation on original image
> (im*add.colour(abs(imlap(out$seg)) == 0)) %>% plot(axes=FALSE)
Error in out$seg : $ operator is invalid for atomic vectors

**Comment by dahtah** [comment]
You need to load purrr, that'll fix the error on the first line

**Comment by alnafisa001** [comment]
Thank you.

**Comment by alnafisa001** [comment]
Hi,
How I make like this image. I have one shape in my output. I need to make three shapes in one image? Please
![302003_combo](https://user-images.githubusercontent.com/10670275/30621760-3b37700e-9d6a-11e7-9116-6dc8c838c0ef.jpg)
