### ISSUE TITLE
Error when i call imager in r 3.3

### ISSUE THREAD

**Issue by issactoast** [dahtah/imager#48]
Hello, I use imager in r but i cannot load the package properly.

system: opensuse leap 42.2
R version: 3.3

when i typed the command below I got error message as follows:
> library(imager)

Error in get(Info[i, 1], envir = env) : 
  cannot open file '/home/issactoast/R/x86_64-suse-linux-gnu-library/3.3/imager/R/imager.rdb': No such file or directory
Error: package or namespace load failed for ‘imager’

**Comment by dahtah** [comment]
OK, that's a strange one. Sometimes devtools corrupts the package loading process, I imagine  you have tried restarting R? Can you maybe run install.packages("imager") again and report the output?

**Comment by issactoast** [comment]
Hey sorry for the late reply, yes i think you were right, i reinstall the
imager and it works well!
