### ISSUE TITLE
Better handling of corrupt files?

### ISSUE THREAD

**Issue by RemkoDuursma** [dahtah/imager#49]
Dear Simon,

great work on imager. I use it to process many files, some of which may be corrupted (somehow).
I was wondering whether `load.image` could be slightly more immune to those files.

Attachment:
![corrupted_file](https://cloud.githubusercontent.com/assets/452362/26629302/279ba8a2-4645-11e7-95da-ef02d9a070d4.jpg)

On `load.image("corrupted_file.jpg")` I get

```
'gm.exe' is not recognized as an internal or external command,
operable program or batch file.
'gm.exe' is not recognized as an internal or external command,
operable program or batch file.
Error in load_image(file) : 
  cimg::stderr(): Reference to 'stderr' stream not allowed in R mode ('cimg_use_r' is defined).
```

I am using `try()` on `load.image` so it is not a major issue, but perhaps can be cleaned up (also, the first two messages cannot be suppressed).

(Windows 7, R 3.4.0, imager 0.40.2)

**Comment by dahtah** [comment]
Hi, thanks for reporting this, you're right, these errors should be handled in a more graceful manner. Will try to fix that soon.

**Comment by dahtah** [comment]
Your particular issue should now be fixed in the current master branch (I still need to work on errors generated by calls to imagemagick).

**Comment by RemkoDuursma** [comment]
Unfortunately compilation fails on my system, but I might have to do some local configuring?

```
../inst/include/CImg.h:451:20: fatal error: tiffio.h: No such file or directory
```

**Comment by dahtah** [comment]
Compiling on Windows is a pain, you need to set up your system just like the CRAN one or it doesn't work. Better to just use winbuilder: here's a [binary](https://win-builder.r-project.org/xX2zlEIQAON8/imager_0.40.2.zip).

**Comment by RemkoDuursma** [comment]
Right, winbuilder is an easy solution. Tested and works great, thanks.
