### ISSUE TITLE
No images can bre loaded without ImageMagic

### ISSUE THREAD

**Issue by slaweks17** [dahtah/imager#5]
On Windows 10, R3.2.3, Imager 0.15, no images could be loaded e.g.
fpath <- system.file('extdata/Leonardo_Birds.jpg',package='imager') 
im <- load.image(fpath) 
would fail on the second line
until ImageMagick was installed. The error was about unrecognized image format.

**Comment by dahtah** [comment]
Thanks for reporting the problem. This bug should be fixed in the 
current master branch. I'll update imager on CRAN.

**Comment by firearasi** [comment]
load.image(system.file('extdata/parrots.png',package='imager'))
'gm.exe' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
'gm.exe' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
'gm.exe' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Error: [instance(0,0,0,0,0000000000000000,non-shared)] CImg<double>::load(): Failed to recognize format of file 'C:\Users\firearasi\Documents\R\win-library\3.2\imager\extdata\parrots.png'.

I have the same problem.
And I cannot successfully install ImageMagick.

**Comment by dahtah** [comment]
Can you try calling
imager:::load.png(system.file('extdata/parrots.png',package='imager'))

That should hopefully do as a workaround for the time being (there's 
also a load.jpg if you need that).

Please let me know if it works.

**Comment by ChanningWong** [comment]
imager:::load.png(.....) works
