### ISSUE TITLE
Documentation problems.

### ISSUE THREAD

**Issue by rorynolan** [dahtah/imager#50]
Hi there,
LOVE your package, working myself on image analysis in R. Just a few things I noticed in the documentation which I think are worth correcting.
1. In the `bucketfill()` example, rather than filling in part of the sail, I get a completely pink image. Also I'm not sure how the `sigma` threshold works from reading the docs.

![pinksail](https://user-images.githubusercontent.com/20400852/27285052-33288f7a-54f3-11e7-8a56-7ad1687cebe0.png)

2. In `common_pixsets` there's a misspelt diamond (it says "diamong" instead).

Thanks,
Rory

**Comment by dahtah** [comment]
Thanks for reporting this, Rory, glad you like the package. Will fix ASAP.

**Comment by dahtah** [comment]
Fixed. The doc for "bucketfill" was a copy-paste from CImg and embarassingly out-of-date. The current master branch has better documentation. Also, you can now specify the colour argument as a colour name (e.g. "red"). 
Don't hesitate if you notice anything else!

**Comment by rorynolan** [comment]
Thanks a lot. I also love the function for working with `magick`.
I'll of course let you know.
Rory
