### ISSUE TITLE
corrupted reference manual

### ISSUE THREAD

**Issue by SymbolixAU** [dahtah/imager#51]
I think the `imager.pdf` reference manual listed on CRAN may have an issue; it never loads for me

https://cran.r-project.org/web/packages/imager/index.html

**Comment by dahtah** [comment]
Thanks for reporting this. Which pdf reader are you using? It opens fine in Firefox and evince.

**Comment by SymbolixAU** [comment]
I was using Chrome (at work) and it wouldn't open at all for the last few days. However, now I'm at home it opened fine (also on Chrome). I'll have to try again on Monday morning. 

Great package by the way 👍

**Comment by SymbolixAU** [comment]
I can no longer reproduce this issue
