### ISSUE TITLE
Abnormal termination occurs when using imshift()

### ISSUE THREAD

**Issue by ShotaOchi** [dahtah/imager#55]
The source code is below.
######
library(imager)
imshift(boats, NA, NA)
######
I'm on windows 7.  The version of imager is 0.40.2.

**Comment by dahtah** [comment]
Thank you, good catch. I've reported it back to as a [CImg issue](https://github.com/dtschump/CImg/issues/158).

**Comment by ShotaOchi** [comment]
Thanks!
