### ISSUE TITLE
No need for Cairo support (?)

### ISSUE THREAD

**Issue by asgr** [dahtah/imager#56]
Hi, as far as I can tell there is no need for Cairo as a import dependency (I've removed it on my local fork). The reason this was an issue for us is some super-computer systems (Cray for sure) have no support for libcairo and we couldn't get things working just for this reason. There might be a reason for it being in the import list, but I couldn't easily spot it.

A

**Comment by dahtah** [comment]
It's used in implot, which enables base graphics on images. The basic idea is to create an in-memory graphics device, use it for plotting, and convert the results back to an image using dev.capture. We could move Cairo to Suggests, and test for availability from within implot.

**Comment by dahtah** [comment]
I should add that I'm not super satisfied with the current implementation of implot, which is slow. So if you have any ideas that could bypass Cairo altogether, I'd be glad to hear them.

**Comment by karldw** [comment]
I want to resurrect this issue because the Cairo dependency has been a sticking point installing the rayshader package, which depends on imager. Could I submit a PR to move Cairo to Suggests?

**Comment by ShotaOchi** [comment]
It's ok to move Cairo to Suggests field because only one function (implot) depends on Cairo and no function depends on implot.
> Suggests: your package can use these packages, but doesn’t require them. You might use 
suggested packages for example datasets, to run tests, build vignettes, or maybe there’s only one function that needs the package.
http://r-pkgs.had.co.nz/description.html

**Comment by asgr** [comment]
Yes, I moved it to Suggests in a local branch I have. Cairo is a nightmare for many machines.
