### ISSUE TITLE
plyr dependency

### ISSUE THREAD

**Issue by Ax3man** [dahtah/imager#57]
Could `plyr` be moved from a Dependency to an Import? Right now attaching `imager` after e.g. `dplyr` will lead to issues as `plyr` is getting attached as well.

Thanks for the very useful package! :thumbsup:

**Comment by dahtah** [comment]
It's a good point, and one that's been on my to-do-list for a while. Let me try and see how many things break.

**Comment by dahtah** [comment]
Done, and now in the master branch. Will update on CRAN soon.

**Comment by Ax3man** [comment]
That's great, thanks a bunch Simon.
