### ISSUE TITLE
suggestion on save.image function name

### ISSUE THREAD

**Issue by Freguglia** [dahtah/imager#58]
I know this is a detail, but in projects I tend to use both `imager::save.image()` and `base::save.image()`, and I often end up writing only `save.image()` when the function I actually want is the masked one. Is it necessary to mask `save.image()` or would changing the function names to something like `image.save()` and `image.load()` be a good idea?

**Comment by dahtah** [comment]
You're right, it's a mistake I made early on and one that'll be hard to fix without breaking a lot of scripts. What I can do is just issue a warning in the next CRAN version, and stop exporting save.image in the one after that.
