### ISSUE TITLE
Support for standard colorscales

### ISSUE THREAD

**Issue by jeremiedb** [dahtah/imager#59]
Is it possible that there's currently no straighforward coloscale function available? For example, a grayscale to jet color transform for example. I noticed such seems easy in the Cimg from https://stackoverflow.com/questions/45421484/having-issues-using-cimg-to-colormap-a-grey-scale-image, but couldn't find an equivalent in the imager package. Thanks!

**Comment by dahtah** [comment]
Here's how to do it using a standard R colour palette (here, hsv) - not super elegant, but good enough:
```
im <- (1+sin(.1*Xc(imfill(100,100))))/2
hsv(h=.2,v=im)  %>% col2rgb  %>% t  %>% as.vector  %>% as.cimg(dim=c(dim(im)[1:3],3))  %>% plot
```
Note that plot.cimg has support for colour scales via the colourscale argument. I'll add a function.

**Comment by jeremiedb** [comment]
Nice, assigning the `im` value into the `h` channel produced exactly what I wanted. 
I noticed the colorscale argument to the plot function, though I wanted to first apply seperatly the colorscale to a mask and then combine with the original image with `imdraw` to produce an activation map. Thanks a lot for quick reply and great package!

![image](https://user-images.githubusercontent.com/18605903/34808184-371628b8-f65b-11e7-93f4-ccc91cd097bf.png)
