### ISSUE TITLE
load.image() error

### ISSUE THREAD

**Issue by Micy1919** [dahtah/imager#6]
require(imager)
im = load.image("text.jpg")

Error: [instance(0,0,0,0,0000000000000000,non-shared)] CImg<double>::load(): Failed to recognize format of file 'D:\r\mxnet\text.jpg'.

**Comment by dahtah** [comment]
Try imager:::load.jpeg("text.jpg")
This should be fixed in the current github version, BTW.

**Comment by Micy1919** [comment]
try imager:::load.image("text.jpg") right! thanks
