### ISSUE TITLE
Mac crash on loading png files

### ISSUE THREAD

**Issue by IanRayner** [dahtah/imager#60]
For example: load.example("parrots") results in:
 *** caught segfault ***
address 0x18, cause 'memory not mapped'

I believe imager uses read.bitmap() from readbitmap package, which in turn uses readPNG() from png package.

I have contacted Peter Urbanak on more than one occasion, filed a bug report, etc., perhaps if the developer of a package that depended upon his were to reach out the problem might be fixed!

It used to work just fine under R3.2, broke when I went to R3.3 and still doesn't work under R3.4.

**Comment by jefferis** [comment]
You can confirm this by getting the path to the parrots example file and then using readPNG directly. Until you do so you haven’t confirmed exactly where the problem lies.

**Comment by IanRayner** [comment]
Thanks for replying so quickly. 

First, should we continue the conversation here or on the readbitmap page?

Second, I have tried reading the parrots.png file in directly, as well as trying a jpg file (which works). Tiff files also fail the same way as a png. I have also tried reading other png / jpg files with the same results. I have also found the the magick package seems to be able to read all the files, and it doesn't use png.

For example:
> test <- system.file("extdata", "parrots.png", package="imager")
> readPNG(test)

results in:
 *** caught segfault ***
address 0x18, cause 'memory not mapped'

Traceback:
 1: .Call(read_png, if (is.raw(source)) source else path.expand(source), native, FALSE)
 2: readPNG(test)

I get the same result with:
>read.bitmap(test)
and 
>load.image(test)
This is how I deduced the problem arose from the png package in the first place.

I was loath to raise this issue with imager or readbitmap because its not really your fault or responsibility. But I figured, after a 6 month wait, that maybe Mr Urbanek might be more responsive to a fellow R package developer who is relying on his png package, than to me!

Hope this extra info helps. Let me know what else you need.

**Comment by IanRayner** [comment]
Since readbitmap is closer to the source of the problem, let's take the discussion there:

[readbitmap](https://github.com/jefferis/readbitmap/issues/2)

I will close this thread.
