### ISSUE TITLE
suggestion of a new vignette about advanced functions in imager

### ISSUE THREAD

**Issue by ShotaOchi** [dahtah/imager#68]
I suggest to add a new vignette about advanced functions in imager.

imager has many utility functions, which enable us to do image processing efficiently.
But the many utility functions make it difficult to find the advanced functions in the reference manual.
So it's painful for newcomers to find the advanced functions implemented in imager.
A new vignette about advanced functions in imager makes it easy for newcomers to see what advanced functions they can use.
That's why I suggest to add it.

What do you think?

**Comment by dahtah** [comment]
Hi Shota. It's a good idea, have to think about what to put in it (also, unfortunately, I've been running against package size limits on CRAN, and vignettes with images in them take up a lot of space). On holiday now, will look into it when I get back.

**Comment by ShotaOchi** [comment]
I'm sorry for my too late reply.
I have no excuse.
We should not add new vignette because new vignette increase package size.
