### ISSUE TITLE
Typo in documentation 

### ISSUE THREAD

**Issue by QuinnVoc** [dahtah/imager#69]
I didn't know where else to put this, so here it is. There is a typo in the documentation of v0.41.1, the most up-to-date version. On page 108, in the description of the asp argument for the plot.cimg function, it says, "Setting asp="varing" means..." The value for asp should say "varying", not "varing". "varing" gives an error and "varying" works as intended.

**Comment by dahtah** [comment]
Thanks for reporting this! It's been fixed (latest master).
