### ISSUE TITLE
Build failed: ‘median’ was not declared in this scope

### ISSUE THREAD

**Issue by Ocirne94** [dahtah/imager#74]
R 3.4.4, Kubuntu 16.04.05.
The error is:
reductions.cpp:226:35: error: ‘median’ was not declared in this scope
The full log of command install.packages("imager") is attached.
[buildLog.txt](https://github.com/dahtah/imager/files/2476915/buildLog.txt)

**Comment by Ocirne94** [comment]
When I run update.packages() I get
[...]
Warning: package 'Rcpp' in library '/usr/lib/R/site-library' will not be updated
[...]
Should I use another command?

In fact I just got the github version of imager, which compiles perfectly.

**Comment by dahtah** [comment]
It means Rcpp was installed as an apt package, and stored in the system-wide library, which only root can change. In this case it's easier to use the CRAN PPA to keep things up-to-date, see https://cran.r-project.org/bin/linux/ubuntu/#installation.
