### ISSUE TITLE
Unable to load shared object. Successful install on OSX but failed to load library?

### ISSUE THREAD

**Issue by michaelSkaro** [dahtah/imager#76]
> install.packages("imager")
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.5/imager_0.41.1.tgz'
Content type 'application/x-gzip' length 9743801 bytes (9.3 MB)
==================================================
downloaded 9.3 MB

The downloaded binary packages are in
	/var/folders/pt/73hcq81s5x728b9n08wh8rt80000gn/T//Rtmp9xsbm0/downloaded_packages

> library(imager)
Error: package or namespace load failed for ‘imager’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/imager/libs/imager.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/imager/libs/imager.so, 6): Library not loaded: /opt/X11/lib/libX11.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/imager/libs/imager.so
  Reason: image not found

**Comment by dahtah** [comment]
You need to install XQuartz. Sorry, the next version of imager will have a more helpful error message

**Comment by michaelSkaro** [comment]
Yes,

I read your manuals page and installed Xquartz as well.

Best,

MS

Sent from my iPhone

On Oct 19, 2018, at 2:18 AM, Simon Barthelmé <notifications@github.com<mailto:notifications@github.com>> wrote:


You need to install XQuartz. Sorry, the next version of imager will have a more helpful error message

**Comment by michaelSkaro** [comment]
Yes, I read your manuals page and installed Xquartz prior to sending the error message.

MS

Sent from my iPhone

On Oct 19, 2018, at 2:18 AM, Simon Barthelmé <notifications@github.com<mailto:notifications@github.com>> wrote:


You need to install XQuartz. Sorry, the next version of imager will have a more helpful error message

**Comment by dahtah** [comment]
Is XQuartz installed under /opt/X11?
