### ISSUE TITLE
Choose color of transparency

### ISSUE THREAD

**Issue by privefl** [dahtah/imager#80]
I'm trying to read this image:

```
library(imager)
img <- load.image("https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Scatter_diagram_for_quality_characteristic_XXX.svg/1000px-Scatter_diagram_for_quality_characteristic_XXX.svg.png")
plot(img)
```

I get a black background where it is transparent in the initial image. 
And I would like this to be white instead.
How can I achieve this?

Thanks

**Comment by ShotaOchi** [comment]
What you need is flatten.alpha function.
Try to use it.
```
img2 <- flatten.alpha(img)
plot(img2)
```

**Comment by privefl** [comment]
Hum, I'm not able to load this image on Windows.

**Comment by privefl** [comment]
On Linux, this does not affect the rendering of the image.

**Comment by dahtah** [comment]
I think you've hit an old bug caused by the weird file name (.svg.png). It's fixed in the current master, also even in the version you have, if you save the file first, then load, then use flatten.alpha, you should be fine.

**Comment by privefl** [comment]
Thanks Simon.
