### ISSUE TITLE
Size Limitation

### ISSUE THREAD

**Issue by AlexanderFraebel** [dahtah/imager#9]
When I try to load large images with imager the result is that the computer locks up and has to be restarted. This seems to happen for anything beyond a few hundred pixels across. I do understand that any scaling should be approximately quadratic but I was surprised that an image of 1000x1000 pixels caused so much trouble when a 500x500 version of the same file loaded instantly.

Is this more likely to do with how imager is designed or limitations of the hardware (laptop) I'm using?

**Comment by dahtah** [comment]
Can you perhaps send me the image that's causing the problem? On my (oldish) laptop loading a 5000x5000 jpeg takes 2 sec. 
Also, what OS are you using? How much free memory?

**Comment by AlexanderFraebel** [comment]
I'm on Windows 10. Looks like there's only about 2GB of RAM free (apparently Firefox and some background processes are taking up a lot more memory than I thought). Looks like its my hardware/resource usage then. Sorry to bother you!
