### ISSUE TITLE
[Request] Building Windows Binary with win-builder.r-project

### ISSUE THREAD

**Issue by ShotaOchi** [dahtah/imager#96]
@dahtah,

Would you build windows binary with win-builder.r-project?

The user of #94 need the bug fixed version of imager on windows.
However, building imager on windows is troublesome.
So, I would appreciate it if you could send the source of imager to win-builder.r-project and 
paste a URL where the binary file can be downloaded from.

Thanks,

**Comment by dahtah** [comment]
Done, available here:
https://win-builder.r-project.org/o1RSQ4x62enR/imager_0.41.1.zip
Hope it works

**Comment by ShotaOchi** [comment]
Thanks!
I confirmed it worked!
